"""Add dating column to users table

Revision ID: 09c57633c134
Revises: b06c578cc911
Create Date: 2023-07-01 00:24:19.294998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09c57633c134'
down_revision = 'b06c578cc911'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('dating', sa.Boolean(), default=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('birthday',
               existing_type=sa.String(length=20),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.drop_column('dating')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
